name: Release

on:
  # Temporarily disabled auto-trigger to prevent accidental releases
  # push:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write  # For creating releases
  packages: write  # For publishing packages

jobs:
  release:
    uses: ./.github/workflows/shared-release.yml
    with:
      version_bump: ${{ github.event.inputs.version_bump }}
      is_test: false
      repository: 'pypi'
      release_prefix: 'v'
      release_title_prefix: 'Release v'
      prerelease: false
      create_release: true
      commit_strategy: 'commit_and_tag'
      branch_condition: 'refs/heads/main'
    secrets:
      api_token: ${{ secrets.PYPI_API_TOKEN }}