# Example: Updated test-release.yml workflow
name: Test Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      fetch-depth: 0
      coverage: false

  test-release:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install uv and supporting tools
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        uv pip install --system toml

    - name: Create test version (no commit)
      id: version
      run: |
        set -e
        CURRENT_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        echo "Current version: $CURRENT_VERSION"
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        TEST_VERSION="${CURRENT_VERSION}.dev${TIMESTAMP}"
        echo "Test version: $TEST_VERSION"
        python -c "import toml; d=toml.load('pyproject.toml'); d['project']['version']='${TEST_VERSION}'; toml.dump(d, open('pyproject.toml','w'))"
        echo "version=$TEST_VERSION" >> $GITHUB_OUTPUT

    # 1. Build the package
    - name: Build package
      uses: ./.github/actions/build-python-package
      with:
        version: ${{ steps.version.outputs.version }}
        package-name: aif-workflow-helper

    # 2. Publish to TestPyPI
    - name: Publish to TestPyPI
      uses: ./.github/actions/publish-python-package
      with:
        version: ${{ steps.version.outputs.version }}
        repository: testpypi
        twine-username: __token__
        twine-password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        package-name: aif-workflow-helper
        test-install: 'true'

    # 3. Create GitHub release
    - name: Create test release
      uses: ./.github/actions/create-github-release
      with:
        release-tag: test-v${{ steps.version.outputs.version }}
        release-title: Test Release v${{ steps.version.outputs.version }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        package-name: aif-workflow-helper
        version: ${{ steps.version.outputs.version }}
        prerelease: 'true'

    - name: Cleanup
      if: always()
      run: |
        git checkout pyproject.toml || true