name: Test Suite

on:
  workflow_call:
    inputs:
      fetch-depth:
        description: 'Git fetch depth for checkout'
        required: false
        default: 1
        type: number
      coverage:
        description: 'Whether to upload coverage to Codecov'
        required: false
        default: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Cache uv global cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install project (editable) + dev deps
      run: |
        uv pip install --system -e .[dev]

    - name: Lint with ruff
      run: |
        uv pip install --system ruff
        ruff check . --output-format=github

    - name: Test with pytest
      run: |
        uv pip install --system coverage
        pytest tests/ -v --tb=short --cov=aif_workflow_helper --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      if: ${{ inputs.coverage && matrix.python-version == '3.12' }}
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  package-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Build & install wheel
      run: |
        uv build
        uv pip install --system dist/*.whl
        aif-workflow-helper --help

    - name: Validate CLI & imports
      run: |
        python -c "import aif_workflow_helper.utils.logging as l; print(l.logger.name)"
        aif-workflow-helper --help | grep "AI Foundry Agent Helper CLI"